services:
#    login.example:
#        class: LoginBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    login.listener.loginobservado_entity:
        class: LoginBundle\Listener\LoginObservadoEntityListener
        arguments:
            session: "@session"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    listener.requestresponse:
        class: LoginBundle\Listener\KernelRequestListener
        arguments: [ @doctrine.orm.entity_manager, @session, @router ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }